# Run these lines one-by-one and if asked to update dependent packages, select yes.

install.packages('rgbif')
install.packages('CoordinateCleaner')
install.packages('rnaturalearthdata')
install.packages('tidysdm')
install.packages('tidyverse')
install.packages('terra')
install.packages('sf')
install.packages('MASS')
install.packages('patchwork')
install.packages('tidyterra')
install.packages('overlapping')
install.packages('ranger')
install.packages('xgboost')
install.packages('DALEX')
install.packages('exactextractr')
install.packages('mapview')
install.packages('blockCV')